### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by wegascee** [xamarindevelopervietnam/xcropimageforms#1]
Are you planning to update the code? I raised the compile target and now I'm getting the following warnings:

>'ProgressDialog' is obsolete: 'This class is obsoleted in this android platform'
>'Canvas.ClipPath(Path, Region.Op)' is obsolete: 'deprecated'
>'View.Invalidate(Rect)' is obsolete: 'deprecated'

Thanks!

**Comment by KennyDizi** [comment]
thanks @wegascee we moving to this plugin where i'm a contributor as well https://github.com/stormlion227/ImageCropper.Forms
